version: 2

sources:
  - name: bubble_raw
    tables:
      - name: batch_child
      - name: chapter
      - name: chapter_school
      - name: child
      - name: child_class
      - name: child_class_section
      - name: child_program
      - name: child_removal_log
      - name: child_subject
      - name: class
      - name: class_section
      - name: class_section_subject
      - name: co_chapter
      - name: partner
      - name: program
      - name: school_class
      - name: school_volunteer
      - name: slot
      - name: slot_class_section
      - name: slot_class_section_volunteer
      - name: subject
      - name: user

  - name: crm_raw
    tables:
      - name: cities
      - name: manager_co
      - name: meetings
      - name: mous
      - name: partner_agreements
      - name: partner_cos
      - name: partners
      - name: poc_partners
      - name: pocs
      - name: states
